development:
  adapter: postgresql
  encoding: unicode
  database: gameplan_development
  pool: 5
  host: localhost
  username: beeker
  password: beeker


test:
  adapter: postgresql
  encoding: unicode
  database: gameplan_test
  pool: 5
  host: localhost
  username: beeker
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gameplan_production
  pool: 5
  host: localhost
  username: beeker
  password: beeker
